<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-K4AMFBT0" failures="1" tests="1" name="TestRunner2(failed)" time="0.16" errors="0" timestamp="2024-11-08T13:13:03 IST">
  <testcase classname="distributedparallel.Test1" name="demo1" time="0.048">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at distributedparallel.Test1.demo1(Test1.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
  <testcase classname="distributedparallel.Test1" name="demo2" time="0.0">
    <ignored/>
  </testcase> <!-- demo2 -->
</testsuite> <!-- TestRunner2(failed) -->
